# Generated by Django 5.1.2 on 2025-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
