# Generated by Django 5.1.2 on 2025-02-02 10:32

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_course_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='published_courses',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=20, validators=[myapp.models.validate_course_duration]),
        ),
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.CharField(max_length=20, validators=[myapp.models.validate_module_duration]),
        ),
    ]
